

export const PAYMENT_CONFRIM_SUCCESS = 'PAYMENT_CONFRIM_SUCCESS';
export const PAYMENT_CONFRIM_FAIL = 'PAYMENT_CONFRIM_FAIL';
export const PAYMENT_CONFRIM_REQUEST = 'PAYMENT_CONFRIM_REQUEST';

export const ORDER_VIDEO_SHOW_REQUEST = 'ORDER_VIDEO_SHOW_REQUEST';
export const ORDER_VIDEO_SHOW_SUCCESS = 'ORDER_VIDEO_SHOW_SUCCESS';
export const ORDER_VIDEO_SHOW_FAIL = 'ORDER_VIDEO_SHOW_FAIL';


export const USER_GET_PAYMENT_VIDEO_ME_REQUEST = 'USER_GET_PAYMENT_VIDEO_ME_REQUEST';
export const USER_GET_PAYMENT_VIDEO_ME_SUCCESS = 'USER_GET_PAYMENT_VIDEO_ME_SUCCESS';
export const USER_GET_PAYMENT_VIDEO_ME_FAIL = 'USER_GET_PAYMENT_VIDEO_ME_FAIL';