export const REGISTER_CREATE_REQUEST = 'REGISTER_CREATE_REQUEST';
export const REGISTER_CREATE_SUCCESS = 'REGISTER_CREATE_SUCCESS';
export const REGISTER_CREATE_FAIL = 'REGISTER_CREATE_FAIL';

export const LOGIN_CREATE_REQUEST = 'LOGIN_CREATE_REQUEST';
export const LOGIN_CREATE_SUCCESS = 'LOGIN_CREATE_SUCCESS';
export const LOGIN_CREATE_FAIL = 'LOGIN_CREATE_FAIL';

export const LOGOUT_CREATE_REQUEST = 'LOGOUT_CREATE_REQUEST';
export const LOGOUT_CREATE_SUCCESS = 'LOGOUT_CREATE_SUCCESS';
export const LOGOUT_CREATE_FAIL = 'LOGOUT_CREATE_FAIL';

export const GET_ALL_USERS_FAIL = 'GET_ALL_USERS_FAIL';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_REQUEST = 'GET_ALL_USERS_REQUEST';


export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const USER_RESET = 'USER_RESET';


export const REGISTER_RESET = 'REGISTER_RESET';


export const PERMISSION_USER_FAIL = 'PERMISSION_USER_FAIL';
export const PERMISSION_USER_REQUEST = 'PERMISSION_USER_REQUEST';
export const PERMISSION_USER_SUCCESS = 'PERMISSION_USER_SUCCESS';


export const ROLE_PERMISSION_USER_FAIL = 'ROLE_PERMISSION_USER_FAIL';
export const ROLE_PERMISSION_USER_REQUEST = 'ROLE_PERMISSION_USER_REQUEST';
export const ROLE_PERMISSION_USER_SUCCESS = 'ROLE_PERMISSION_USER_SUCCESS';

export const UPDATE_USER_INFO_SUCCESS = 'UPDATE_USER_INFO_SUCCESS';
export const UPDATE_USER_INFO_FAIL = 'UPDATE_USER_INFO_FAIL';
export const UPDATE_USER_INFO_REQUEST = 'UPDATE_USER_INFO_REQUEST';

export const FORGET_PASSWORD_EMAIL_REQUEST = 'FORGET_PASSWORD_EMAIL_REQUEST';
export const FORGET_PASSWORD_EMAIL_SUCCESS = 'FORGET_PASSWORD_EMAIL_SUCCESS';
export const FORGET_PASSWORD_EMAIL_FAIL = 'FORGET_PASSWORD_EMAIL_FAIL';


export const FORGET_PASSWORD_RESET_REQUEST = 'FORGET_PASSWORD_RESET_REQUEST';
export const FORGET_PASSWORD_RESET_SUCCESS = 'FORGET_PASSWORD_RESET_SUCCESS';
export const FORGET_PASSWORD_RESET_FAIL = 'FORGET_PASSWORD_RESET_FAIL';