export const CREATE_VIDEO_REQUEST = 'CREATE_VIDEO_REQUEST';
export const CREATE_VIDEO_SUCCESS = 'CREATE_VIDEO_SUCCESS';
export const CREATE_VIDEO_FAIL = 'CREATE_VIDEO_FAIL';

export const VIDEO_RESET = 'VIDEO_RESET';

export const GET_ALL_VIDEOS_FAIL = 'GET_ALL_VIDEOS_FAIL';
export const GET_ALL_VIDEOS_REQUEST = 'GET_ALL_VIDEOS_REQUEST';
export const GET_ALL_VIDEOS_SUCCESS  = 'GET_ALL_VIDEOS_SUCCESS';

export const GET_ALL_ADMIN_VIDEOS_FAIL = 'GET_ALL_ADMIN_VIDEOS_FAIL';
export const GET_ALL_ADMIN_VIDEOS_REQUEST = 'GET_ALL_ADMIN_VIDEOS_REQUEST';
export const GET_ALL_ADMIN_VIDEOS_SUCCESS  = 'GET_ALL_ADMIN_VIDEOS_SUCCESS';

export const DELETE_VIDEOS_FAIL = 'DELETE_VIDEOS_FAIL';
export const DELETE_VIDEOS_REQUEST = 'DELETE_VIDEOS_REQUEST' ;
export const DELETE_VIDEOS_SUCCESS  = 'DELETE_VIDEOS_SUCCESS';

export const UPDATE_VIDEOS_FAIL = 'UPDATE_VIDEOS_FAIL';
export const UPDATE_VIDEOS_REQUEST = 'UPDATE_VIDEOS_REQUEST';
export const UPDATE_VIDEOS_SUCCESS  = 'UPDATE_VIDEOS_SUCCESS';

export const CREATE_GROUPS_VIDEO_SUCCESS = 'CREATE_GROUPS_VIDEO_SUCCESS';
export const CREATE_GROUPS_VIDEO_REQUEST = 'CREATE_GROUPS_VIDEO_REQUEST';
export const CREATE_GROUPS_VIDEO_FAIL = 'CREATE_GROUPS_VIDEO_FAIL';

export const GET_NAME_GROUPS_VIDEO_SUCCESS = 'GET_NAME_GROUPS_VIDEO_SUCCESS';
export const GET_NAME_GROUPS_VIDEO_FAIL = 'GET_NAME_GROUPS_VIDEO_FAIL';
export const GET_NAME_GROUPS_VIDEO_REQUEST = 'GET_NAME_GROUPS_VIDEO_REQUEST';
export const RESET_VIDEO_GROUPS_NAME = 'RESET_VIDEO_GROUPS_NAME';

export const CREATE_VIDEOS_GROUPS_VIDEO_SUCCESS = 'CREATE_VIDEOS_GROUPS_VIDEO_SUCCESS';
export const CREATE_VIDEOS_GROUPS_VIDEO_REQUEST = 'CREATE_VIDEOS_GROUPS_VIDEO_REQUEST';
export const CREATE_VIDEOS_GROUPS_VIDEO_FAIL = 'CREATE_VIDEOS_GROUPS_VIDEO_FAIL';


export const GET_VIDEOS_GROUPS_SINGLE_SUCCESS = 'GET_VIDEOS_GROUPS_SINGLE_SUCCESS';
export const GET_VIDEOS_GROUPS_SINGLE_FAIL = 'GET_VIDEOS_GROUPS_SINGLE_FAIL';
export const GET_VIDEOS_GROUPS_SINGLE_REQUEST = 'GET_VIDEOS_GROUPS_SINGLE_REQUEST';


export const GET_SINGLE_VIDEOS_OF_USER_REQUEST = 'GET_SINGLE_VIDEOS_OF_USER_REQUEST';
export const GET_SINGLE_VIDEOS_OF_USER_SUCCESS = 'GET_SINGLE_VIDEOS_OF_USER_SUCCESS';
export const GET_SINGLE_VIDEOS_OF_USER_FAIL = 'GET_SINGLE_VIDEOS_OF_USER_FAIL';

export const GET_GROUPS_VIDEOS_OF_USER_REQUEST = 'GET_GROUPS_VIDEOS_OF_USER_REQUEST';
export const GET_GROUPS_VIDEOS_OF_USER_SUCCESS = 'GET_GROUPS_VIDEOS_OF_USER_SUCCESS';
export const GET_GROUPS_VIDEOS_OF_USER_FAIL = 'GET_GROUPS_VIDEOS_OF_USER_FAIL';

export const GET_GROUPS_VIDEOS_USER_UNIQUE_SUCCESS = 'GET_GROUPS_VIDEOS_USER_UNIQUE_SUCCESS';
export const GET_GROUPS_VIDEOS_USER_UNIQUE_REQUEST = 'GET_GROUPS_VIDEOS_USER_UNIQUE_REQUEST';
export const GET_GROUPS_VIDEOS_USER_UNIQUE_FAIL = 'GET_GROUPS_VIDEOS_USER_UNIQUE_FAIL';

export const GET_SINGLE_VIDEO_REQUEST = 'GET_SINGLE_VIDEO_REQUEST';
export const GET_SINGLE_VIDEO_FAIL = 'GET_SINGLE_VIDEO_FAIL';
export const GET_SINGLE_VIDEO_SUCCESS = 'GET_SINGLE_VIDEO_SUCCESS';

export const VIDEO_LIKE_REQUEST = 'VIDEO_LIKE_REQUEST';
export const VIDEO_LIKE_SUCCESS = 'VIDEO_LIKE_SUCCESS';
export const VIDEO_LIKE_FAIL = 'VIDEO_LIKE_FAIL';

export const VIDEO_COMMEND_GET_REQUEST = 'VIDEO_COMMEND_GET_REQUEST';
export const VIDEO_COMMEND_GET_SUCCESS = 'VIDEO_COMMEND_GET_SUCCESS';
export const VIDEO_COMMEND_GET_FAIL = 'VIDEO_COMMEND_GET_FAIL';
export const VIDEO_COMMEND_CREATE_REQUEST = 'VIDEO_COMMEND_CREATE_REQUEST';
export const VIDEO_COMMEND_CREATE_SUCCESS = 'VIDEO_COMMEND_CREATE_SUCCESS';
export const VIDEO_COMMEND_CREATE_FAIL = 'VIDEO_COMMEND_CREATE_FAIL';
export const RESET_USER_VIDEOS = 'RESET_USER_VIDEOS';

export const POSTER_CREATE_REQUEST = 'POSTER_CREATE_REQUEST';
export const POSTER_CREATE_SUCCESS = 'POSTER_CREATE_SUCCESS';
export const POSTER_CREATE_FAIL = 'POSTER_CREATE_FAIL';
export const POSTER_CREATE_RESET = 'POSTER_CREATE_RESET';

export const POSTER_GET_REQUEST = 'POSTER_GET_REQUEST';
export const POSTER_GET_SUCCESS = 'POSTER_GET_SUCCESS';
export const POSTER_GET_FAIL = 'POSTER_GET_FAIL';

export const POSTER_DELETE_REQUEST = 'POSTER_DELETE_REQUEST';
export const POSTER_DELETE_SUCCESS = 'POSTER_DELETE_SUCCESS';
export const POSTER_DELETE_FAIL = 'POSTER_DELETE_FAIL';

export const POSTER_GET_ALL_REQUEST = 'POSTER_GET_ALL_REQUEST ';
export const POSTER_GET_ALL_SUCCESS = 'POSTER_GET_ALL_SUCCESS';
export const POSTER_GET_ALL_FAIL = 'POSTER_GET_ALL_FAIL';

export const POSTER_GET_SINGLE_REQUEST = 'POSTER_GET_SINGLE_REQUEST ';
export const POSTER_GET_SINGLE_SUCCESS = 'POSTER_GET_SINGLE_SUCCESS';
export const POSTER_GET_SINGLE_FAIL = 'POSTER_GET_SINGLE_FAIL';

export const POSTER_CREATE_REVIEW_REQUEST = 'POSTER_CREATE_REVIEW_REQUEST ';
export const POSTER_CREATE_REVIEW_SUCCESS = 'POSTER_CREATE_REVIEW_SUCCESS';
export const POSTER_CREATE_REVIEW_FAIL = 'POSTER_CREATE_REVIEW_FAIL';